<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Main Page</title>
</head>
</html>
<head>
    <link type='text/css' rel='stylesheet' href='css/custom.css'/>
<body>
<table class=scrollable_table>
    <tr class=calendar_row>
        <td class=calendar_td></td>
        <td class=calendar_td></td>
        <td class=calendar_td></td>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-01" class = "link">1
                <div class=calendar_num></div>

            </a>
        </td>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-02" class = "link">2
                <div class=calendar_num></div>
            </a>
        </td>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-03" class = "link">3
                <div class=calendar_num></div>
            </a>
        </td>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-04" class = "link">4
                <div class=calendar_num></div>
            </a>
        </td>
    </tr>
    <tr class=calendar_row>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-05" class = "link">5
                <div class=calendar_num></div>
            </a>
        </td>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-06" class = "link">6
                <div class=calendar_num></div>
            </a>
        </td>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-07" class = "link">7
                <div class=calendar_num></div>
            </a>
        </td>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-08" class = "link">8
                <div class=calendar_num></div>
            </a>
        </td>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-09" class = "link">9
                <div class=calendar_num></div>
            </a>
        </td>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-10" class = "link">10
                <div class=calendar_num></div>
            </a>
        </td>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-11" class = "link">11
                <div class=calendar_num></div>
            </a>
        </td>
    </tr>
    <tr class=calendar_row>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-12" class = "link">12
                <div class=calendar_num></div>
            </a>
        </td>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-13" class = "link">13
                <div class=calendar_num></div>
            </a>
        </td>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-14" class = "link">14
                <div class=calendar_num></div>
            </a>
        </td>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-15" class = "link">15
                <div class=calendar_num></div>
            </a>
        </td>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-16" class = "link">16
                <div class=calendar_num></div>
            </a>
        </td>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-17" class = "link">17
                <div class=calendar_num></div>
            </a>
        </td>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-18" class = "link">18
                <div class=calendar_num></div>
            </a>
        </td>
    </tr>
    <tr class=calendar_row>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-19" class = "link">19
                <div class=calendar_num></div>
            </a>
        </td>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-20" class = "link">20
                <div class=calendar_num></div>
            </a>
        </td>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-21" class = "link">21
                <div class=calendar_num></div>
            </a>
        </td>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-22" class = "link">22
                <div class=calendar_num></div>
            </a>
        </td>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-23" class = "link">23
                <div class=calendar_num></div>
            </a>
        </td>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-24" class = "link">24
                <div class=calendar_num></div>
            </a>
        </td>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-25" class = "link">25
                <div class=calendar_num></div>
            </a>
        </td>
    </tr>
    <tr class=calendar_row>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-26" class = "link">26
                <div class=calendar_num></div>
            </a>
        </td>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-27" class = "link">27
                <div class=calendar_num></div>
            </a>
        </td>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-28" class = "link">28
                <div class=calendar_num></div>
            </a>
        </td>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-29" class = "link">29
                <div class=calendar_num></div>
            </a>
        </td>
        <td class=calendar_td>
            <a href="/tasks?date=2021-04-30" class = "link">30
                <div class=calendar_num></div>
            </a>
        </td>
        <td class=calendar_td></td>
        <td class=calendar_td></td>
    </tr>
</table>
</body>
</html>